global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'milapp-backend-production'
    static_configs:
      - targets: ['backend-production:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'milapp-frontend-production'
    static_configs:
      - targets: ['frontend-production:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'redis-production'
    static_configs:
      - targets: ['redis-production:6379']
    scrape_interval: 30s

  - job_name: 'minio-production'
    static_configs:
      - targets: ['minio-production:9000']
    scrape_interval: 30s

  - job_name: 'prometheus-production'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  - job_name: 'nginx-production'
    static_configs:
      - targets: ['nginx-production:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s 