global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'milapp-backend-staging'
    static_configs:
      - targets: ['backend-staging:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'milapp-frontend-staging'
    static_configs:
      - targets: ['frontend-staging:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'redis-staging'
    static_configs:
      - targets: ['redis-staging:6379']
    scrape_interval: 30s

  - job_name: 'minio-staging'
    static_configs:
      - targets: ['minio-staging:9000']
    scrape_interval: 30s

  - job_name: 'prometheus-staging'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s 