global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MILAPP MedSênior Application
  - job_name: 'milapp-medsenior'
    static_configs:
      - targets: ['milapp-medsenior-prod:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*)'
        replacement: 'milapp-medsenior-${1}'

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['milapp-medsenior-prod:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Recording rules for MedSênior KPIs
rule_files:
  - "medsenior-rules.yml" 