version: '3.8'

services:
  milapp-medsenior:
    build: .
    container_name: milapp-medsenior-app
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_APP_NAME=MILAPP MedSênior
      - VITE_APP_VERSION=2.0.0
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - VITE_OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost/health.json"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.milapp.rule=Host(`milapp.medsenior.local`)"
      - "com.medsenior.service=milapp"
      - "com.medsenior.version=2.0.0"

  # Supabase local para desenvolvimento
  supabase-db:
    image: supabase/postgres:latest
    container_name: milapp-supabase-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: medsenior123
      POSTGRES_DB: milapp_dev
    volumes:
      - supabase_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  supabase_data:
    name: milapp-medsenior-db 