// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktuvnllzmpsdgstsgbib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dXZubGx6bXBzZGdzdHNnYmliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDc0ODcsImV4cCI6MjA2NzQ4MzQ4N30.j2HUJeQ9nX0stgWTDeGLNf2eWW0s6KO-KRsYg50YicI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});